services:
  db:
    image: postgres:14.19-alpine3.21
    container_name: motivora-db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: motivora
      POSTGRES_PASSWORD: motivora
      POSTGRES_DB: motivora_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:9.9
    container_name: motivora-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@motivora.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db


  smtp4dev:
    container_name: smtp4dev
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '8082:80'
      # Change the number before : to the port the SMTP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '9025:25'
      # Change the number before : to the port the IMAP server should be accessible on
      # Add 127.0.0.1: prefix for localhost-only access (recommended for security)
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
        - smtp4dev-data:/smtp4dev

volumes:
  postgres-data:
  smtp4dev-data: